package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_binary")


py_binary(
    name = "foo",
    srcs = ["foo.py"],
    deps = [
        "//foo/bar",
        ],

)
